apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v1
  labels:
    app: guestbook
    version: "1.0"
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        version: "1.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: guestbook
        image: linsun/guestbookv1:latest
        ports:
        - name: http-server
          containerPort: 3000
