apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v2
  labels:
    app: guestbook
    version: "2.0"
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 1 
  template:
    metadata:
      labels:
        app: guestbook
        version: "2.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: guestbook
        image: linsun/guestbookv2:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 3000
